name: build and deploy 

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/weeduo-it/all4esthetic:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy-gh
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin <<< "${{ secrets.GHCR_TOKEN }}"
            cd /var/www/all4esthetic.com
            git pull
            docker stack deploy -c docker-compose.yml all4esthetic
